const validValues = {
  weapons: [
    "axe",
    "book",
    "bow",
    "chain weapon",
    "claw",
    "club",
    "crossbow",
    "dagger",
    "grenade",
    "hammer",
    "instrument",
    "lance",
    "mace",
    "natural weapons",
    "pistol",
    "polearm",
    "rifle",
    "rocket pack",
    "scroll",
    "scythe",
    "spear",
    "spell effect",
    "staff",
    "standard",
    "sword",
    "sword-staff",
  ],
  armor: ["cloak", "clothing", "leather", "mail", "plate", "powered armor", "robe", "shield"],
  race: [
    "draconian",
    "dragonspawn",
    "dwarf",
    "elf",
    "goblin",
    "golem",
    "half-orc",
    "halfling",
    "human",
    "lizardfolk",
    "lupine",
    "obsidiman",
    "ogre",
    "stonechild",
    "tabaxi",
    "t'skrang",
    "troll",
    "undead",
    "unknown",
    "warjack",
  ],
  status: ["prepainted", "unpainted", "wip", "painted", "unassembled", undefined],
};

module.exports = validValues;
