const validTags = {
  genre: ["fantasy", "magitek", "monstrosity", "sci-fi", "western"],
  race: [
    "alien",
    "blightspawn",
    "catfolk",
    "dragonfolk",
    "dwarf",
    "elf",
    "goblinoid",
    "golem",
    "half-orc",
    "halfling",
    "human",
    "lizardfolk",
    "obsidiman",
    "ogre",
    "orc",
    "ratfolk",
    "robot",
    "troll",
    "undead",
    "unknown",
    "warjack",
    "wulfen",
  ],
  archetype: [
    "artificer",
    "cleric",
    "druid",
    "fighter",
    "monk",
    "mounted",
    "paladin",
    "ranger",
    "rogue",
    "techie",
    "wizard",
  ],
  weapons: [
    "axe",
    "battle standard",
    "bow",
    "buzzsaw",
    "chain weapon",
    "club",
    "crossbow",
    "dagger",
    "explosives",
    "fighting claw",
    "firearm",
    "great weapon",
    "hammer",
    "musical instrument",
    "mace",
    "natural weapons",
    "polearm",
    "scythe",
    "spear",
    "spell effect",
    "spell focus",
    "staff",
    "sword",
    "sword-staff",
    "technology",
    "whip",
  ],
  armor: ["cloak", "clothing", "leather", "mail", "plate", "powered armor", "robe", "shield"],
  status: ["prepainted", "unpainted", "wip", "painted", "unassembled"],
  minidb: {
    status: ["hidden", "draft", "todo", "published"],
  },
  gallery: {
    status: ["hidden", "draft", "todo", "published"],
  },
};

module.exports = validTags;
